public void getLastDataCallFailCause(Message result){
    throw new RuntimeException("getLastDataCallFailCause not expected to be called");
}